const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');
const CLASSES={acorazada:{name:'Acorazada',hp:150,energy:70,attack:14,defense:12,speed:205,skills:['Cañón pesado','Pulso de desafío','Impulso de embestida']},energia:{name:'Energía',hp:85,energy:160,attack:18,defense:4,speed:215,skills:['Ráfaga de plasma','Nova de energía','Salto vectorial']},interceptora:{name:'Interceptora',hp:105,energy:110,attack:16,defense:7,speed:235,skills:['Disparo preciso','Ráfaga múltiple','Maniobra evasiva']},soporte:{name:'Soporte',hp:115,energy:145,attack:9,defense:8,speed:215,skills:['Nanorreparación','Escudo aliado','Pulso restaurador']}};
const DEFAULT={name:'Nave Aurora',classId:null,level:1,x:0,y:0,hp:100,maxHp:100,energy:100,maxEnergy:100,attack:10,defense:5,gold:0,xp:0,speed:220,quests:{}};
const QUESTS={primer_camino:{id:'primer_camino',title:'Señal desconocida',giver:'eldrin',type:'explore',target:'east_gate',required:1,description:'Investiga el corredor este de la Estación Aurora.',reward:{xp:75,gold:40},intro:'Los sensores detectan una señal desconocida fuera de la estación. Cruza el corredor este e investiga el sector.',complete:'Bien hecho. Ya tenemos datos del sector exterior.'},cazador:{id:'cazador',title:'Drones hostiles',giver:'eldrin',type:'kill',target:'hostile_drone',required:3,description:'Destruye 3 drones hostiles del sector.',reward:{xp:120,gold:70}},recolector:{id:'recolector',title:'Componentes de reparación',giver:'mara',type:'collect',target:'repair_component',required:4,description:'Recupera 4 componentes de reparación.',reward:{xp:90,gold:55}},guardian:{id:'guardian',title:'Acorazado renegado',giver:'eldrin',type:'boss',target:'renegade_dreadnought',required:1,description:'Destruye el Acorazado Renegado.',reward:{xp:350,gold:200}}};
let player={...DEFAULT,...JSON.parse(localStorage.getItem('mundoAbierto.player')||'{}')};player.quests=player.quests||{};player.xp=player.xp||0;
const keys={}, joy={x:0,y:0}; let last=performance.now(),projectiles=[],fireCd=0,skillCooldown=0,lastAim={x:1,y:0};
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)} addEventListener('resize',resize);resize();
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const j=document.querySelector('#joystick'),s=document.querySelector('#stick');
function moveStick(e){const r=j.getBoundingClientRect(),t=e.touches?e.touches[0]:e;let x=t.clientX-(r.left+r.width/2),y=t.clientY-(r.top+r.height/2),m=Math.hypot(x,y),lim=45;if(m>lim){x=x/m*lim;y=y/m*lim}joy.x=x/lim;joy.y=y/lim;s.style.transform='translate('+x+'px,'+y+'px)'}
j.addEventListener('pointerdown',e=>{j.setPointerCapture(e.pointerId);moveStick(e)});j.addEventListener('pointermove',e=>{if(j.hasPointerCapture(e.pointerId))moveStick(e)});j.addEventListener('pointerup',()=>{joy.x=joy.y=0;s.style.transform=''});
function save(){localStorage.setItem('mundoAbierto.player',JSON.stringify(player))}
function questState(id){return player.quests[id]||null}
function acceptQuest(id){const q=QUESTS[id];if(!q||questState(id))return;player.quests[id]={status:'active',progress:0};save();renderQuestTracker();renderDialogueQuestAction()}
function addQuestProgress(type,target,amount=1){for(const q of Object.values(QUESTS)){const s=questState(q.id);if(s?.status==='active'&&q.type===type&&q.target===target){s.progress=Math.min(q.required,s.progress+amount);if(s.progress>=q.required)s.status='ready';save();renderQuestTracker()}}}
function completeQuest(id){const q=QUESTS[id],s=questState(id);if(!q||s?.status!=='ready')return;s.status='completed';player.gold+=q.reward.gold;gainXp(q.reward.xp);save();renderQuestTracker();hud();renderDialogueQuestAction()}
function renderQuestTracker(){const active=Object.values(QUESTS).find(q=>['active','ready'].includes(questState(q.id)?.status));questTracker.classList.toggle('hidden',!active);if(!active)return;const s=questState(active.id);questTitle.textContent=(s.status==='ready'?'✓ ':'')+active.title;questObjective.textContent=s.status==='ready'?'Regresa con '+NPCS.find(n=>n.id===active.giver)?.name:active.description+' ('+s.progress+'/'+active.required+')';questProgressBar.style.width=(s.progress/active.required*100)+'%';questReward.textContent='Recompensa: '+active.reward.xp+' XP · '+active.reward.gold+' oro'}
function getNpcQuest(npc){return Object.values(QUESTS).find(q=>q.giver===npc.id&&(q.id==='primer_camino'||questState(q.id)))|| (npc.id==='eldrin'?QUESTS.primer_camino:null)}
function renderDialogueQuestAction(){questAction.classList.add('hidden');if(!activeNpc)return;const q=getNpcQuest(activeNpc);if(!q)return;const s=questState(q.id);if(!s){questAction.textContent='Aceptar contrato: '+q.title;questAction.onclick=()=>acceptQuest(q.id);questAction.classList.remove('hidden')}else if(s.status==='ready'){questAction.textContent='Completar contrato';questAction.onclick=()=>completeQuest(q.id);questAction.classList.remove('hidden')}}
function xpNeeded(level=player.level){return 100+(level-1)*65}
function gainXp(amount){player.xp+=amount;while(player.xp>=xpNeeded()){player.xp-=xpNeeded();levelUp()}hud()}
function levelUp(){player.level++;const hpGain=10+Math.floor(player.level/3)*2,enGain=5,atkGain=2,defGain=1;player.maxHp+=hpGain;player.maxEnergy+=enGain;player.attack+=atkGain;player.defense+=defGain;player.hp=player.maxHp;player.energy=player.maxEnergy;levelToast.innerHTML='⭐ NIVEL '+player.level+'<small>Casco +'+hpGain+' · Energía +'+enGain+' · Potencia +'+atkGain+' · Escudo +'+defGain+'</small>';levelToast.classList.remove('hidden');clearTimeout(levelToast._timer);levelToast._timer=setTimeout(()=>levelToast.classList.add('hidden'),2600);save()}
function chooseClass(id){const c=CLASSES[id];if(!c)return;player.classId=id;player.maxHp=c.hp;player.hp=c.hp;player.maxEnergy=c.energy;player.energy=c.energy;player.attack=c.attack;player.defense=c.defense;player.speed=c.speed;renderClassPicker();hud()}
function renderClassPicker(){const box=document.querySelector('.class-grid');if(!box)return;box.innerHTML=Object.entries(CLASSES).map(([id,c])=>'<button type="button" class="class-card '+(player.classId===id?'selected':'')+'" data-class="'+id+'"><b>'+c.name+'</b><small>❤ '+c.hp+' · ⚔ '+c.attack+' · 🛡 '+c.defense+'</small><small>'+c.skills.join(' · ')+'</small></button>').join('');box.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>chooseClass(b.dataset.class))}
setInterval(save,5000);addEventListener('beforeunload',save);
function hud(){playerName.textContent=player.name;classLabel.textContent=player.classId?CLASSES[player.classId].name:'Sin tipo';level.textContent='Nivel '+player.level;hpText.textContent=player.hp+'/'+player.maxHp;energyText.textContent=player.energy+'/'+player.maxEnergy;hpBar.style.width=player.hp/player.maxHp*100+'%';energyBar.style.width=player.energy/player.maxEnergy*100+'%';attack.textContent=player.attack;defense.textContent=player.defense;gold.textContent=player.gold;const need=xpNeeded();xpText.textContent='XP '+Math.floor(player.xp)+' / '+need;xpBar.style.width=Math.min(100,player.xp/need*100)+'%'}
const NPCS=[{id:'mara',name:'MARA-7',role:'Operadora de hangar',x:-320,y:-80,color:'#c76b74',dialogue:['Bienvenido a la Estación Aurora, piloto. El hangar está disponible para tu nave.','Cuando regreses dañado, podremos reparar el casco y recargar tus sistemas.']},{id:'borin',name:'BORIN',role:'Ingeniero jefe',x:-315,y:390,color:'#8a6048',dialogue:['Una nave bien calibrada sobrevive donde otras quedan a la deriva.','Recupera tecnología del sector y podré mejorar armas, escudos y motores.']},{id:'lira',name:'LIRA',role:'Comerciante orbital',x:335,y:-90,color:'#5d83c4',dialogue:['Bienvenido, piloto. Siempre consigo módulos interesantes.','Aquí podrás comprar suministros y vender componentes recuperados.']},{id:'eldrin',name:'ELDRIN',role:'Comandante de operaciones',x:350,y:390,color:'#8063b5',dialogue:['Los sensores registran actividad anómala fuera de Aurora.','Cuando estés preparado tendré un contrato de reconocimiento para ti.']}];
let nearbyNpc=null,activeNpc=null,dialogueStep=0;
const WORLD={minX:-1200,maxX:3600,minY:-1800,maxY:1800};
const LANDMARKS=[{x:1250,y:-520,name:'Baliza abandonada'},{x:1750,y:520,name:'Nebulosa Esmeralda'},{x:2350,y:-650,name:'Ruinas orbitales'},{x:3050,y:250,name:'Sector Umbral'}];
const ASTEROIDS=Array.from({length:90},(_,i)=>({x:900+((i*431)%2500),y:-1500+((i*719)%3000),r:8+(i%5)*4})).filter(t=>Math.abs(t.y)>150||t.x>1500);
const ENEMY_TYPES={scout:{name:'Dron Explorador',hp:35,speed:120,damage:5,detect:300,leash:520,range:55,color:'#e65757',respawn:7,xp:18},raider:{name:'Caza Saqueador',hp:55,speed:150,damage:8,detect:360,leash:600,range:70,color:'#e78b45',respawn:9,xp:28},sentinel:{name:'Centinela Renegado',hp:90,speed:90,damage:12,detect:390,leash:650,range:85,color:'#b86bd9',respawn:12,xp:45}};
const ENEMIES=[['scout',1180,-260],['scout',1380,250],['scout',1580,-420],['raider',1850,450],['raider',2150,-320],['raider',2500,180],['sentinel',2780,-520],['sentinel',3200,360]].map((e,i)=>{const t=ENEMY_TYPES[e[0]];return{id:'enemy_'+i,type:e[0],homeX:e[1],homeY:e[2],x:e[1],y:e[2],hp:t.hp,maxHp:t.hp,state:'patrol',angle:i,attackCd:0,deadUntil:0}});
const TOWN={half:760,buildings:[{x:-420,y:-260,w:190,h:150,name:'Hangar'},{x:230,y:-280,w:210,h:160,name:'Mercado orbital'},{x:-430,y:210,w:210,h:150,name:'Ingeniería'},{x:250,y:210,w:200,h:150,name:'Operaciones'}]};
function drawTown(w,h){const sx=x=>w/2+(x-player.x),sy=y=>h/2+(y-player.y);ctx.fillStyle='#18293d';ctx.fillRect(sx(-TOWN.half),sy(-TOWN.half),TOWN.half*2,TOWN.half*2);ctx.fillStyle='#263f5b';ctx.fillRect(sx(-90),sy(-TOWN.half),180,TOWN.half*2);ctx.fillRect(sx(-TOWN.half),sy(-90),TOWN.half*2,180);ctx.fillStyle='#142236';for(const b of TOWN.buildings){const x=sx(b.x),y=sy(b.y);ctx.fillStyle='#31455c';ctx.fillRect(x,y,b.w,b.h);ctx.fillStyle='#55728f';ctx.beginPath();ctx.moveTo(x-15,y);ctx.lineTo(x+b.w/2,y-70);ctx.lineTo(x+b.w+15,y);ctx.fill();ctx.fillStyle='#fff';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText(b.name,x+b.w/2,y+b.h+20)}ctx.fillStyle='#657e96';ctx.beginPath();ctx.arc(sx(0),sy(0),65,0,Math.PI*2);ctx.fill();ctx.fillStyle='#29a5d6';ctx.beginPath();ctx.arc(sx(0),sy(0),42,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 16px system-ui';ctx.fillText('Estación Aurora',sx(0),sy(-105));ctx.font='12px system-ui';ctx.fillText('Zona segura · escudos activos',sx(0),sy(-87));for(const n of NPCS){const nx=sx(n.x),ny=sy(n.y);ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(nx,ny,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.fillText(n.name,nx,ny-27);ctx.font='10px system-ui';ctx.fillText(n.role,nx,ny+34)}}
function drawRegion(w,h){const sx=x=>w/2+(x-player.x),sy=y=>h/2+(y-player.y);ctx.fillStyle='#07101f';ctx.fillRect(sx(760),sy(WORLD.minY),WORLD.maxX-760,WORLD.maxY-WORLD.minY);ctx.strokeStyle='#152d4c';ctx.lineWidth=95;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(sx(650),sy(0));ctx.bezierCurveTo(sx(1300),sy(30),sx(1750),sy(350),sx(2200),sy(50));ctx.bezierCurveTo(sx(2700),sy(-250),sx(3100),sy(150),sx(3500),sy(0));ctx.stroke();ctx.lineWidth=1;for(const t of ASTEROIDS){ctx.fillStyle='#5c6270';ctx.beginPath();ctx.arc(sx(t.x),sy(t.y),t.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#818896';ctx.stroke()}for(const p of LANDMARKS){ctx.fillStyle='#f2df9b';ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(p.name,sx(p.x),sy(p.y)-15)}ctx.fillStyle='#d7c183';ctx.fillRect(sx(745),sy(-115),35,230);ctx.fillStyle='#fff';ctx.font='bold 13px system-ui';ctx.fillText('Corredor Este',sx(900),sy(-135))}
function updateEnemies(dt,now){const safe=Math.abs(player.x)<=TOWN.half&&Math.abs(player.y)<=TOWN.half;for(const e of ENEMIES){const t=ENEMY_TYPES[e.type];if(e.state==='dead'){if(now>=e.deadUntil){e.x=e.homeX;e.y=e.homeY;e.hp=t.hp;e.state='patrol'}else continue}e.attackCd=Math.max(0,e.attackCd-dt);const dp=Math.hypot(player.x-e.x,player.y-e.y),dh=Math.hypot(e.x-e.homeX,e.y-e.homeY);if(!safe&&dp<t.detect&&dh<t.leash)e.state='chase';if(safe||dh>t.leash)e.state='return';let tx,ty,spd=t.speed;if(e.state==='chase'){tx=player.x;ty=player.y;if(dp<=t.range){spd=0;if(e.attackCd<=0){player.hp=Math.max(0,player.hp-Math.max(1,t.damage-Math.floor(player.defense*.25)));e.attackCd=1.2}}}else if(e.state==='return'){tx=e.homeX;ty=e.homeY;if(dh<12)e.state='patrol'}else{e.angle+=dt*.55;tx=e.homeX+Math.cos(e.angle)*70;ty=e.homeY+Math.sin(e.angle)*70;spd*=.45}const d=Math.hypot(tx-e.x,ty-e.y);if(d>2&&spd){e.x+=(tx-e.x)/d*spd*dt;e.y+=(ty-e.y)/d*spd*dt}}}
function nearestEnemy(max=650){let best=null,dist=max;for(const e of ENEMIES){if(e.state==='dead')continue;const d=Math.hypot(e.x-player.x,e.y-player.y);if(d<dist){best=e;dist=d}}return best}
function destroyEnemy(e,now){const t=ENEMY_TYPES[e.type];e.state='dead';e.deadUntil=now+t.respawn;e.hp=0;addQuestProgress('kill','hostile_drone');player.gold+=5;gainXp(t.xp);save()}
function fire(mult=1,count=1){if(activeNpc||fireCd>0)return;const target=nearestEnemy(),a=target?Math.atan2(target.y-player.y,target.x-player.x):Math.atan2(lastAim.y,lastAim.x);for(let i=0;i<count;i++){const spread=(i-(count-1)/2)*.12,ang=a+spread;projectiles.push({x:player.x,y:player.y,vx:Math.cos(ang)*620,vy:Math.sin(ang)*620,life:1.2,damage:player.attack*mult})}fireCd=.28}
function useSkill(){if(!player.classId||skillCooldown>0||activeNpc)return;const id=player.classId;if(id==='acorazada'){if(player.energy<25)return;player.energy-=25;fire(2.4,1);skillCooldown=5}else if(id==='energia'){if(player.energy<35)return;player.energy-=35;for(const e of ENEMIES){if(e.state!=='dead'&&Math.hypot(e.x-player.x,e.y-player.y)<230){e.hp-=player.attack*1.8;if(e.hp<=0)destroyEnemy(e,performance.now()/1000)}}skillCooldown=7}else if(id==='interceptora'){if(player.energy<30)return;player.energy-=30;fire(1.1,3);skillCooldown=5}else if(id==='soporte'){if(player.energy<30)return;player.energy-=30;player.hp=Math.min(player.maxHp,player.hp+Math.round(player.maxHp*.35));skillCooldown=8}}
function updateCombat(dt,now){fireCd=Math.max(0,fireCd-dt);skillCooldown=Math.max(0,skillCooldown-dt);player.energy=Math.min(player.maxEnergy,player.energy+8*dt);for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)continue;for(const e of ENEMIES){if(e.state==='dead')continue;if(Math.hypot(p.x-e.x,p.y-e.y)<28){e.hp-=p.damage;p.life=0;e.state='chase';if(e.hp<=0)destroyEnemy(e,now);break}}}projectiles=projectiles.filter(p=>p.life>0);skillCd.textContent=skillCooldown>0?Math.ceil(skillCooldown)+'s':''}
function drawProjectiles(w,h){for(const p of projectiles){const x=w/2+(p.x-player.x),y=h/2+(p.y-player.y);ctx.fillStyle='#72e7ff';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill()}}
function drawEnemies(w,h){const sx=x=>w/2+(x-player.x),sy=y=>h/2+(y-player.y);for(const e of ENEMIES){if(e.state==='dead')continue;const t=ENEMY_TYPES[e.type],x=sx(e.x),y=sy(e.y);ctx.save();ctx.translate(x,y);ctx.fillStyle=t.color;ctx.beginPath();ctx.moveTo(-20,-14);ctx.lineTo(22,0);ctx.lineTo(-20,14);ctx.lineTo(-10,0);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#000b';ctx.fillRect(x-24,y-27,48,5);ctx.fillStyle='#ef5350';ctx.fillRect(x-24,y-27,48*(e.hp/e.maxHp),5);ctx.fillStyle='#fff';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(t.name,x,y-34)}}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#030712';ctx.fillRect(0,0,w,h);drawRegion(w,h);drawTown(w,h);drawEnemies(w,h);drawProjectiles(w,h);ctx.strokeStyle='#ffffff0d';ctx.lineWidth=1;const grid=80,ox=((w/2-player.x)%grid+grid)%grid,oy=((h/2-player.y)%grid+grid)%grid;for(let x=ox;x<w;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=oy;y<h;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.save();ctx.translate(w/2,h/2);ctx.fillStyle='#59bfff';ctx.beginPath();ctx.moveTo(28,0);ctx.lineTo(-18,-16);ctx.lineTo(-10,0);ctx.lineTo(-18,16);ctx.closePath();ctx.fill();ctx.fillStyle='#d9f6ff';ctx.fillRect(-15,-5,17,10);ctx.restore();ctx.fillStyle='#fff';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(player.name,w/2,h/2-30)}
function updateInteraction(){if(activeNpc)return;nearbyNpc=null;let best=85;for(const n of NPCS){const d=Math.hypot(player.x-n.x,player.y-n.y);if(d<best){best=d;nearbyNpc=n}}interactBtn.classList.toggle('hidden',!nearbyNpc);if(nearbyNpc)interactBtn.textContent='Hablar con '+nearbyNpc.name}
function openDialogue(){if(!nearbyNpc)return;activeNpc=nearbyNpc;dialogueStep=0;dialogueName.textContent=activeNpc.name;dialogueRole.textContent=activeNpc.role;const q=getNpcQuest(activeNpc),qs=q&&questState(q.id);dialogueText.textContent=q&&!qs?q.intro:(q&&qs?.status==='ready'?q.complete:activeNpc.dialogue[0]);dialogue.classList.remove('hidden');renderDialogueQuestAction();interactBtn.classList.add('hidden')}
function closeDialogue(){dialogue.classList.add('hidden');questAction.classList.add('hidden');activeNpc=null;dialogueStep=0}
function nextDialogue(){if(!activeNpc)return;dialogueStep++;if(dialogueStep>=activeNpc.dialogue.length)return closeDialogue();dialogueText.textContent=activeNpc.dialogue[dialogueStep]}
fireBtn.onpointerdown=()=>fire();skillBtn.onpointerdown=useSkill;interactBtn.onclick=openDialogue;dialogueNext.onclick=nextDialogue;dialogueClose.onclick=closeDialogue;addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();fire()}if(e.key.toLowerCase()==='q')useSkill();if(e.key.toLowerCase()==='e'&&!e.repeat){if(activeNpc)nextDialogue();else openDialogue()}if(e.key==='Escape'&&activeNpc)closeDialogue()});
function loop(now){let dt=Math.min((now-last)/1000,.05);last=now;updateCombat(dt,now/1000);updateEnemies(dt,now/1000);let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x,y=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+joy.y,m=Math.hypot(x,y);if(m>1){x/=m;y/=m}if(Math.hypot(x,y)>.1)lastAim={x,y};if(activeNpc){x=0;y=0}player.x+=x*player.speed*dt;player.y+=y*player.speed*dt;player.x=Math.max(WORLD.minX,Math.min(WORLD.maxX,player.x));player.y=Math.max(WORLD.minY,Math.min(WORLD.maxY,player.y));if(player.hp<=0){player.x=0;player.y=0;player.hp=player.maxHp;player.energy=player.maxEnergy}if(questState('primer_camino')?.status==='active'&&player.x>820)addQuestProgress('explore','east_gate');updateInteraction();draw();hud();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const panel=document.querySelector('#characterPanel'),nameInput=document.querySelector('#nameInput');
characterBtn.onclick=()=>{nameInput.value=player.name;renderClassPicker();statList.innerHTML='Nivel: '+player.level+' · XP: '+Math.floor(player.xp)+'/'+xpNeeded()+'<br>Casco: '+player.maxHp+'<br>Energía: '+player.maxEnergy+'<br>Potencia: '+player.attack+'<br>Escudo: '+player.defense;panel.classList.remove('hidden')};closePanel.onclick=()=>panel.classList.add('hidden');
saveBtn.onclick=()=>{player.name=(nameInput.value.trim()||'Nave Aurora').slice(0,16);save();hud();panel.classList.add('hidden')};
resetBtn.onclick=()=>{if(confirm('¿Reiniciar la nave y todo su progreso?')){player={...DEFAULT,quests:{}};save();renderClassPicker();renderQuestTracker();panel.classList.add('hidden')}};renderQuestTracker();hud();