const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');
const CLASSES={guerrero:{name:'Guerrero',hp:150,energy:70,attack:14,defense:12,speed:205,skills:['Golpe poderoso','Provocar','Carga']},mago:{name:'Mago',hp:85,energy:160,attack:18,defense:4,speed:215,skills:['Bola de fuego','Nova arcana','Teletransporte']},arquero:{name:'Arquero',hp:105,energy:110,attack:16,defense:7,speed:235,skills:['Disparo preciso','Lluvia de flechas','Evasión']},sanador:{name:'Sanador',hp:115,energy:145,attack:9,defense:8,speed:215,skills:['Curación','Luz protectora','Pulso vital']}};
const DEFAULT={name:'Aventurero',classId:null,level:1,x:0,y:0,hp:100,maxHp:100,energy:100,maxEnergy:100,attack:10,defense:5,gold:0,xp:0,speed:220,quests:{}};
const QUESTS={primer_camino:{id:'primer_camino',title:'El camino inquieto',giver:'eldrin',type:'explore',target:'east_gate',required:1,description:'Explora la salida este de Villa del Alba.',reward:{xp:75,gold:40},intro:'Los viajeros hablan de ruidos extraños fuera de la villa. Ve hasta la salida este y observa el camino.',complete:'Bien hecho. Has dado el primer paso fuera de la seguridad de la villa.'},cazador:{id:'cazador',title:'Problemas en el camino',giver:'eldrin',type:'kill',target:'slime',required:3,description:'Derrota 3 criaturas del camino.',reward:{xp:120,gold:70}},recolector:{id:'recolector',title:'Hierbas para Mara',giver:'mara',type:'collect',target:'healing_herb',required:4,description:'Recoge 4 hierbas curativas.',reward:{xp:90,gold:55}},guardian:{id:'guardian',title:'El guardián del bosque',giver:'eldrin',type:'boss',target:'forest_guardian',required:1,description:'Derrota al Guardián del Bosque.',reward:{xp:350,gold:200}}};
let player={...DEFAULT,...JSON.parse(localStorage.getItem('mundoAbierto.player')||'{}')};player.quests=player.quests||{};player.xp=player.xp||0;
const keys={}, joy={x:0,y:0}; let last=performance.now();
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)} addEventListener('resize',resize);resize();
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const j=document.querySelector('#joystick'),s=document.querySelector('#stick');
function moveStick(e){const r=j.getBoundingClientRect(),t=e.touches?e.touches[0]:e;let x=t.clientX-(r.left+r.width/2),y=t.clientY-(r.top+r.height/2),m=Math.hypot(x,y),lim=45;if(m>lim){x=x/m*lim;y=y/m*lim}joy.x=x/lim;joy.y=y/lim;s.style.transform='translate('+x+'px,'+y+'px)'}
j.addEventListener('pointerdown',e=>{j.setPointerCapture(e.pointerId);moveStick(e)});j.addEventListener('pointermove',e=>{if(j.hasPointerCapture(e.pointerId))moveStick(e)});j.addEventListener('pointerup',()=>{joy.x=joy.y=0;s.style.transform=''});
function save(){localStorage.setItem('mundoAbierto.player',JSON.stringify(player))}
function questState(id){return player.quests[id]||null}
function acceptQuest(id){const q=QUESTS[id];if(!q||questState(id))return;player.quests[id]={status:'active',progress:0};save();renderQuestTracker();renderDialogueQuestAction()}
function addQuestProgress(type,target,amount=1){for(const q of Object.values(QUESTS)){const s=questState(q.id);if(s?.status==='active'&&q.type===type&&q.target===target){s.progress=Math.min(q.required,s.progress+amount);if(s.progress>=q.required)s.status='ready';save();renderQuestTracker()}}}
function completeQuest(id){const q=QUESTS[id],s=questState(id);if(!q||s?.status!=='ready')return;s.status='completed';player.gold+=q.reward.gold;player.xp+=q.reward.xp;save();renderQuestTracker();hud();renderDialogueQuestAction()}
function renderQuestTracker(){const active=Object.values(QUESTS).find(q=>['active','ready'].includes(questState(q.id)?.status));questTracker.classList.toggle('hidden',!active);if(!active)return;const s=questState(active.id);questTitle.textContent=(s.status==='ready'?'✓ ':'')+active.title;questObjective.textContent=s.status==='ready'?'Regresa con '+NPCS.find(n=>n.id===active.giver)?.name:active.description+' ('+s.progress+'/'+active.required+')';questProgressBar.style.width=(s.progress/active.required*100)+'%';questReward.textContent='Recompensa: '+active.reward.xp+' XP · '+active.reward.gold+' oro'}
function getNpcQuest(npc){return Object.values(QUESTS).find(q=>q.giver===npc.id&&(q.id==='primer_camino'||questState(q.id)))|| (npc.id==='eldrin'?QUESTS.primer_camino:null)}
function renderDialogueQuestAction(){questAction.classList.add('hidden');if(!activeNpc)return;const q=getNpcQuest(activeNpc);if(!q)return;const s=questState(q.id);if(!s){questAction.textContent='Aceptar: '+q.title;questAction.onclick=()=>acceptQuest(q.id);questAction.classList.remove('hidden')}else if(s.status==='ready'){questAction.textContent='Entregar misión';questAction.onclick=()=>completeQuest(q.id);questAction.classList.remove('hidden')}}
function chooseClass(id){const c=CLASSES[id];if(!c)return;player.classId=id;player.maxHp=c.hp;player.hp=c.hp;player.maxEnergy=c.energy;player.energy=c.energy;player.attack=c.attack;player.defense=c.defense;player.speed=c.speed;renderClassPicker();hud()}
function renderClassPicker(){const box=document.querySelector('.class-grid');if(!box)return;box.innerHTML=Object.entries(CLASSES).map(([id,c])=>'<button type="button" class="class-card '+(player.classId===id?'selected':'')+'" data-class="'+id+'"><b>'+c.name+'</b><small>❤ '+c.hp+' · ⚔ '+c.attack+' · 🛡 '+c.defense+'</small><small>'+c.skills.join(' · ')+'</small></button>').join('');box.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>chooseClass(b.dataset.class))}
setInterval(save,5000);addEventListener('beforeunload',save);
function hud(){playerName.textContent=player.name;classLabel.textContent=player.classId?CLASSES[player.classId].name:'Sin clase';level.textContent='Nivel '+player.level;hpText.textContent=player.hp+'/'+player.maxHp;energyText.textContent=player.energy+'/'+player.maxEnergy;hpBar.style.width=player.hp/player.maxHp*100+'%';energyBar.style.width=player.energy/player.maxEnergy*100+'%';attack.textContent=player.attack;defense.textContent=player.defense;gold.textContent=player.gold}
const NPCS=[{id:'mara',name:'Mara',role:'Posadera',x:-320,y:-80,color:'#c76b74',dialogue:['¡Bienvenido a Villa del Alba! La posada siempre tiene una cama para los viajeros.','Cuando regreses herido de una aventura, ven a verme. Pronto podré ayudarte a descansar y recuperarte.']},{id:'borin',name:'Borin',role:'Herrero',x:-315,y:390,color:'#8a6048',dialogue:['Un arma bien cuidada puede decidir una batalla.','Tráeme materiales cuando empieces a explorar. Más adelante podré mejorar tu equipo.']},{id:'lira',name:'Lira',role:'Mercader',x:335,y:-90,color:'#5d83c4',dialogue:['¡Mira con calma, aventurero! Siempre intento conseguir mercancía útil.','Cuando la tienda abra podrás comprar suministros y vender el botín que encuentres.']},{id:'eldrin',name:'Eldrin',role:'Sabio',x:350,y:390,color:'#8063b5',dialogue:['Algo inquieta los caminos más allá de la villa.','Cuando estés preparado tendré una tarea para ti. Será el comienzo de tu primera aventura.']}];
let nearbyNpc=null,activeNpc=null,dialogueStep=0;
const TOWN={half:760,buildings:[{x:-420,y:-260,w:190,h:150,name:'Posada'},{x:230,y:-280,w:210,h:160,name:'Tienda'},{x:-430,y:210,w:210,h:150,name:'Herrero'},{x:250,y:210,w:200,h:150,name:'Casa del Sabio'}]};
function drawTown(w,h){const sx=x=>w/2+(x-player.x),sy=y=>h/2+(y-player.y);ctx.fillStyle='#b9a36a';ctx.fillRect(sx(-TOWN.half),sy(-TOWN.half),TOWN.half*2,TOWN.half*2);ctx.fillStyle='#d8c68a';ctx.fillRect(sx(-90),sy(-TOWN.half),180,TOWN.half*2);ctx.fillRect(sx(-TOWN.half),sy(-90),TOWN.half*2,180);ctx.fillStyle='#78a55b';for(const b of TOWN.buildings){const x=sx(b.x),y=sy(b.y);ctx.fillStyle='#6d4931';ctx.fillRect(x,y,b.w,b.h);ctx.fillStyle='#a9563c';ctx.beginPath();ctx.moveTo(x-15,y);ctx.lineTo(x+b.w/2,y-70);ctx.lineTo(x+b.w+15,y);ctx.fill();ctx.fillStyle='#fff';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText(b.name,x+b.w/2,y+b.h+20)}ctx.fillStyle='#e5d39a';ctx.beginPath();ctx.arc(sx(0),sy(0),65,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4f86b8';ctx.beginPath();ctx.arc(sx(0),sy(0),42,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 16px system-ui';ctx.fillText('Villa del Alba',sx(0),sy(-105));ctx.font='12px system-ui';ctx.fillText('Zona segura',sx(0),sy(-87));for(const n of NPCS){const nx=sx(n.x),ny=sy(n.y);ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(nx,ny,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.fillText(n.name,nx,ny-27);ctx.font='10px system-ui';ctx.fillText(n.role,nx,ny+34)}}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#315f39';ctx.fillRect(0,0,w,h);drawTown(w,h);ctx.strokeStyle='#ffffff0d';ctx.lineWidth=1;const grid=80,ox=((w/2-player.x)%grid+grid)%grid,oy=((h/2-player.y)%grid+grid)%grid;for(let x=ox;x<w;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=oy;y<h;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.fillStyle='#d6a635';ctx.beginPath();ctx.arc(w/2,h/2,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(player.name,w/2,h/2-30)}
function updateInteraction(){if(activeNpc)return;nearbyNpc=null;let best=85;for(const n of NPCS){const d=Math.hypot(player.x-n.x,player.y-n.y);if(d<best){best=d;nearbyNpc=n}}interactBtn.classList.toggle('hidden',!nearbyNpc);if(nearbyNpc)interactBtn.textContent='Hablar con '+nearbyNpc.name}
function openDialogue(){if(!nearbyNpc)return;activeNpc=nearbyNpc;dialogueStep=0;dialogueName.textContent=activeNpc.name;dialogueRole.textContent=activeNpc.role;const q=getNpcQuest(activeNpc),qs=q&&questState(q.id);dialogueText.textContent=q&&!qs?q.intro:(q&&qs?.status==='ready'?q.complete:activeNpc.dialogue[0]);dialogue.classList.remove('hidden');renderDialogueQuestAction();interactBtn.classList.add('hidden')}
function closeDialogue(){dialogue.classList.add('hidden');questAction.classList.add('hidden');activeNpc=null;dialogueStep=0}
function nextDialogue(){if(!activeNpc)return;dialogueStep++;if(dialogueStep>=activeNpc.dialogue.length)return closeDialogue();dialogueText.textContent=activeNpc.dialogue[dialogueStep]}
interactBtn.onclick=openDialogue;dialogueNext.onclick=nextDialogue;dialogueClose.onclick=closeDialogue;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&!e.repeat){if(activeNpc)nextDialogue();else openDialogue()}if(e.key==='Escape'&&activeNpc)closeDialogue()});
function loop(now){let dt=Math.min((now-last)/1000,.05);last=now;let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x,y=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+joy.y,m=Math.hypot(x,y);if(m>1){x/=m;y/=m}player.x+=x*player.speed*dt;player.y+=y*player.speed*dt;player.x=Math.max(-1050,Math.min(1050,player.x));player.y=Math.max(-1050,Math.min(1050,player.y));if(questState('primer_camino')?.status==='active'&&player.x>900)addQuestProgress('explore','east_gate');updateInteraction();draw();hud();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const panel=document.querySelector('#characterPanel'),nameInput=document.querySelector('#nameInput');
characterBtn.onclick=()=>{nameInput.value=player.name;renderClassPicker();statList.innerHTML='Nivel: '+player.level+'<br>Vida: '+player.maxHp+'<br>Energía: '+player.maxEnergy+'<br>Ataque: '+player.attack+'<br>Defensa: '+player.defense;panel.classList.remove('hidden')};closePanel.onclick=()=>panel.classList.add('hidden');
saveBtn.onclick=()=>{player.name=(nameInput.value.trim()||'Aventurero').slice(0,16);save();hud();panel.classList.add('hidden')};
resetBtn.onclick=()=>{if(confirm('¿Reiniciar el personaje?')){player={...DEFAULT,quests:{}};save();renderClassPicker();renderQuestTracker();panel.classList.add('hidden')}};renderQuestTracker();hud();